#include "config.h"

#define ACTIVE_HIGH_RELAY true
#define ACTION_TIME 0
#define DEBOUNCE_TIME 2000
#define RELAY_ACTIVE_TIME 500

// Fan Parameters
#define MQTT_FAN_ACTION_TOPIC MQTT_CLIENTID "/FAN/SET"
#define MQTT_FAN_STATUS_TOPIC MQTT_CLIENTID "/FAN/STATE"
#define MQTT_FANSPEED_ACTION_TOPIC MQTT_CLIENTID "/FAN/SPEED/SET"
#define MQTT_FANSPEED_STATUS_TOPIC MQTT_CLIENTID "/FAN/SPEED/STATE"
#define FAN_ON_PAYLOAD "FAN_ON"
#define FAN_OFF_PAYLOAD "FAN_OFF"
#define FAN_LOW_PAYLOAD "FAN_LOW"
#define FAN_MED_PAYLOAD "FAN_MED"
#define FAN_HIGH_PAYLOAD "FAN_HIGH"
#define FAN_OFF_PIN 5
#define FAN_LOW_PIN 14
#define FAN_MED_PIN 12
#define FAN_HIGH_PIN 16
#define FAN_ON_DELAY 50


// Light Parameters
#define MQTT_LIGHT_ACTION_TOPIC MQTT_CLIENTID "/LIGHT/SET"
#define MQTT_LIGHT_STATUS_TOPIC MQTT_CLIENTID "/LIGHT/STATE"
#define LIGHT_ON_PAYLOAD "LIGHT_ON"
#define LIGHT_OFF_PAYLOAD "LIGHT_OFF"
#define LIGHT_ON_PIN 13
#define LIGHT_OFF_PIN 13
//command topic

#define MQTT_COMMAND_ACTION_TOPIC MQTT_CLIENTID "/COMMAND"
#define LIGHT_INVERT_PAYLOAD "INVERT_LIGHT"
